name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    uses: RaphaelIT7/gmodcommon-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "eightbit"
      BUILD_64x: "true"
      REALM: "sv"
